name: Discord Daily Alarm

on:
  schedule:
    - cron: '40 22 * * *'  # 매일 22:40 UTC → 한국시간(KST) 기준 다음날 07:40

jobs:
  send_alarm:
    runs-on: ubuntu-latest
    env:
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v3

      - name: Python 설정
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 의존성 설치
        run: pip install requests

      - name: 알람 스크립트 실행
        run: python morning-alarm.py
